-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/27/2015 23:33:48
-- Server version: 5.6.20
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE db_jbexh;

--
-- Definition for table tbl_admin
--
DROP TABLE IF EXISTS tbl_admin;
CREATE TABLE tbl_admin (
  id INT(10) NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) DEFAULT NULL,
  password VARCHAR(15) DEFAULT NULL,
  level VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_event
--
DROP TABLE IF EXISTS tbl_event;
CREATE TABLE tbl_event (
  event_id INT(11) NOT NULL AUTO_INCREMENT,
  event_name VARCHAR(50) DEFAULT NULL,
  event_desc TEXT DEFAULT NULL,
  event_date DATETIME DEFAULT NULL,
  event_pic VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (event_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 13
AVG_ROW_LENGTH = 1638
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table tbl_admin
--
INSERT INTO tbl_admin VALUES
(3, 'admin', 'admin', 'admin');

-- 
-- Dumping data for table tbl_event
--
INSERT INTO tbl_event VALUES
(1, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 08:04:49', ''),
(2, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:13', ''),
(3, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:15', ''),
(4, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:17', ''),
(5, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:19', ''),
(6, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:21', ''),
(7, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:23', ''),
(8, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:24', ''),
(9, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:28', ''),
(10, 'Blue Plaza Bekasi', 'Dalam rangka membantu Perusahaan untuk mendapatkan kandidat yang sesuai harapan Perusahaan dan sekaligus Program Pemerintah dengan salah satu tujuannya adalah mengurangi pengangguran dan kemiskinan, Sehubungan dengan hal tersebut diatas kami menyelenggara', '2015-12-27 10:11:30', '');

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;